"""create register_token table

Revision ID: 497710512b11
Revises: 
Create Date: 2022-01-28 10:42:27.330301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497710512b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aiueo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiueo',

    )
    op.drop_table('register_token')
    # ### end Alembic commands ###
