"""fix property name

Revision ID: eedd00c1e0be
Revises: 3c46777ef815
Create Date: 2022-01-28 12:55:11.225966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedd00c1e0be'
down_revision = '3c46777ef815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
